services:
  z2api:
    build: .
    container_name: z2api-server
    ports:
      - "3002:8000"
    environment:
      - HOST=${HOST:-0.0.0.0} # 监听地址
      - PORT=${PORT:-8000} # 监听端口
      - API_KEY=${API_KEY:-sk-z2api-key-2024} # 鉴权密钥
      - SHOW_THINK_TAGS=${SHOW_THINK_TAGS:-false} # 思考标签
      - DEFAULT_STREAM=${DEFAULT_STREAM:-false} # 流式
      - Z_AI_COOKIES=${Z_AI_COOKIES} # Z.AI的JWT令牌
      - LOG_LEVEL=${LOG_LEVEL:-ERROR} # 日志级别

      # 自动刷新设置 (当前未实现)
      - AUTO_REFRESH_TOKENS=${AUTO_REFRESH_TOKENS:-false} # 是否自动刷新令牌
      - REFRESH_CHECK_INTERVAL=${REFRESH_CHECK_INTERVAL:-3600} # 刷新检查间隔(秒)
      
      # 连接池设置
      - MAX_CONNECTIONS=${MAX_CONNECTIONS:-50} # 最大连接数
      - MAX_KEEPALIVE_CONNECTIONS=${MAX_KEEPALIVE_CONNECTIONS:-20} # 最大保持活动连接数
      - KEEPALIVE_EXPIRY=${KEEPALIVE_EXPIRY:-30} # 连接保持时间(秒)
    volumes:
      # 可选：挂载日志目录
      - logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - z2api-network

  # 可选：添加Nginx反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: z2api-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - z2api
  #   restart: unless-stopped
  #   networks:
  #     - z2api-network
  #   profiles:
  #     - with-nginx

networks:
  z2api-network:
    driver: bridge

volumes:
  logs:
    driver: local
